### ISSUE TITLE
Have a way of searching all files for matches

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_advancedreplace#22]
This will be a new cli script sibling to cli/find.php and lets call it cli/find-in-files.php and rename the old on to file-in-database.php

* [ ] This will have basically the same params as the db one for searching
* [x] we are searching the files in mdl_files
* [x] it will produce a similar csv file, but instead of referencing the table and column it will have columns for the component and file area
* [x] for each record we pull down the file to temp and search it inside php
* [ ] we'll have a second replace script which takes the input + a new column and replaces the contents in the file and reuploads it via the file api

**Comment by picnicpete** [comment]
- It is obvious to put command line filters for component and area. 
- I wonder if we should filter by mime type.  Avoid searching all those jpeg files for 'doris'.
- Maybe have a --no-binary-files option that excludes a bunch of mime types.
- Some files are compressed or zipped or encrypted and might need special attention.
- Maybe h5p is zipped?
- (How) can we link these to courseid?

- I have made the searches case insensitive.
- (Maybe the database search should be insensitive as well.)
- I have implemented regex search.  Do we need a plain string search? Seems like extra fog to me. (It made sense on the database because it uses a different SQL clause, but that does not apply here.)
